name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Analyse complète du code source

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'  # JDK 23 utilisé pour correspondre à votre configuration
        distribution: 'temurin'

    - name: Compile Java Project
      run: |
        mkdir -p MissieMoustass/bin
        javac -d MissieMoustass/bin $(find MissieMoustass/src/Main -name "*.java")

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour les informations sur les PR
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Token généré sur SonarCloud.io
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_SCANNER_OPTS: "-X"  # Active le mode debug
