name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Permet une analyse complète du code, pas un clone partiel

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Compile Java project
      run: |
        mkdir -p MissieMoustass/bin
        javac -d MissieMoustass/bin $(find MissieMoustass/src/Main -name "*.java")

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_PROJECT_KEY: ben-sliman_TpMissieMoustass
        SONAR_ORGANIZATION: ben-sliman
