name: Build for snarCloud
 
on:

  push:

    branches:

      - main

  pull_request:

    types: [opened, synchronize, reopened]

jobs:

  sonarcloud:

    name: SonarCloud

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

        with:

          fetch-depth: 0
 
      - name: Set up JDK 23

        uses: actions/setup-java@v3

        with:

          java-version: '23'

          distribution: 'temurin'
 
      - name: SonarCloud Scan

        uses: SonarSource/sonarcloud-github-action@main

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information

          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io
 
