name: Java CI/CD on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Java project
      run: |
        mkdir -p bin
        javac -d bin $(findfind /Users/iziben/Documents/École/Qualité\ de\ Code\ Source/TpMissieMoustass/MissieMoustass -name "*.java")

    - name: Run tests (if JUnit is used)
      run: |
        if ls src | grep -q "Test"; then
          java -cp bin org.junit.runner.JUnitCore $(find src -name "*Test.java" | sed 's/src\///;s/\.java//' | tr '/' '.')
        else
          echo "No tests found, skipping."

  deploy:
    runs-on: macos-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Deploy Application
      run: |
        echo "Deploying application..."
        # Add deployment script or command here
        echo "Deployment successful."
