name: Java CI/CD on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Compile Java project
      run: |
        mkdir -p bin
        javac -d bin $(find MissieMoustass -name "*.java")

    - name: Run tests (JUnit)
      run: |
        if find MissieMoustass -name "*Test.java" | grep -q .; then
          java -cp bin org.junit.runner.JUnitCore $(find MissieMoustass -name "*Test.java" | sed 's/MissieMoustass\///;s/\.java//' | tr '/' '.')
        else
          echo "No tests found, skipping."

  deploy:
    runs-on: macos-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Deploy Application
      run: |
        echo "Déploiement de l'application..."
        # Ajoutez vos commandes spécifiques ici
        echo "Déploiement terminé avec succès."
