name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Créer un dossier de build
        run: mkdir -p build

      - name: Compiler l'application
        run: javac -cp "lib/*" -d build $(find src -name "*.java")

      - name: Vérifier les fichiers compilés
        run: ls -la build

      - name: Exécuter l'application
        run: java -cp "build:lib/*" Main.Login
